#!/usr/bin/env sh
set -eux

curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz | tar -xJf -
mv ffmpeg-*-static/ffmpeg /usr/local/bin/
mv ffmpeg-*-static/ffprobe /usr/local/bin/
rm -rf ffmpeg-*-static
